
GET http://localhost:8080/hat/api/regions/California/counties
content-type: application/json

{
}

###

GET http://localhost:8080/hat/api/regions/states
content-type: application/json

{
}

###

GET http://localhost:8080/hat/api/regions/California/metros
content-type: application/json

{
}

###

GET http://localhost:8080/hat/api/historical/values/state/California
content-type: application/json

{
}

###

GET http://localhost:8080/hat/api/historical/values/state/Florida
content-type: application/json

{
}

###

GET http://localhost:8080/hat/api/historical/values/US
content-type: application/json

{
}

###
GET http://localhost:8080/hat/api/analytics/states
content-type: application/json

{
}

###

